<?php
	$controller = $this->getController();
	$modules = $this->param('modules');
	$config = $this->param('config');

	$devzone = $this->param('devzone_config');
?>

<h2>System Development</h2>

<h3>Change log - Version <?= $devzone["project"]["build"] ?></h3>

<p>
<ul>
	<?php foreach ($devzone["project"]["changelog"] as $change): ?>
		<li><?= $change ?></li>
	<?php endforeach; ?>
</ul>
</p>

<h3>File table</h3>
<?php
	$_SESSION["buffer"] = array();
	$_SESSION["buffer"]["lines"] = 0;
	$_SESSION["buffer"]["characters"] = 0;
?>
<div class="table-responsive">
	<table class="table table-striped table-hover table-sm table-bordered">
		<thead class="thead-dark">
			<tr>
				<th scope="col">Path</th>
				<th scope="col"># lines / dirs</th>
				<th scope="col"># characters / files</th>
			</tr>
		</thead>
		<tbody>
			<tr class="table-success"><td colspan='3'><h3 class="display-4">Business logic (MVC)</h3></td></tr>
			<?php $controller->ls($modules) ?>
			<tr class="table-success"><td colspan='3'><h3 class="display-4">Config files</h3></td></tr>
			<?php $controller->ls($config) ?>
		</tbody>
		<tfoot>
			<tr>
				<td></td>
				<td></td>
				<td></td>
			</tr>
			<tr>
				<td></td>
				<td><span class='badge badge-danger' style='font-size: 25px'><?= number_format($_SESSION["buffer"]["lines"]) ?> lines</span></td>
				<td><span class='badge badge-danger' style='font-size: 25px'><?= number_format($_SESSION["buffer"]["characters"]) ?> characters</span></td>
			</tr>
		</tfoot>
	</table>
</div>