<?php
    $config = $this->param('project');

    $routing = $this->param('routing');
    $fd = $routing["friendly"]
?>

<div class="$ black-shadow slow jumbotron well enlighten">
    <h1 class="$ slide-left-in">
        <?= $config["name"] ?>
    </h1>
    <p class="$ slide-right-in">
        <?= $config["description"] ?>
    </p>
    <p class="$ fade-in infinite slow">
        <img src="<?= $this->basePath() ?>/public/img/plts-logo.png" alt="logo" class="$ fade-out infinite slow" />
    </p>
    <a href="<?= $this->basePath() ?>/public/<?= ($fd) ? 'DevZone/Index/development' : '?module=DevZone&controller=Index&view=development' ?>" class="btn btn-default"><span class="glyphicon glyphicon-link"></span> View Release</a>
</div>

<div class="$ slide-right-in row clearfix" style="margin-top: 20px">
    <div class="col-md-6 column">
        <p>
            Build <?= $config["build"] ?>
        </p>
    </div>
    <div class="col-md-6 column">
        <p>
        Copyright <strong>(c)</strong> 2017 Pleets - DronePHP Framework module
        </p>
    </div>
</div>