<?php
    $config = $this->param('project');

    $routing = $this->param('routing');
    $fd = $routing["friendly"]
?>

<div class="jumbotron well enlighten">
    <h1 class="display-4">
        <?= $config["name"] ?>
    </h1>
    <p class="lead">
        <?= $config["description"] ?>
        <br />
    </p>
    <hr class="my-4" />
    <a href="<?= $this->basePath() ?>/public/<?= ($fd) ? 'DevZone/Index/development' : '?module=DevZone&controller=Index&view=development' ?>"
       class="btn btn-info btn-lg"><span class="glyphicon glyphicon-link"></span>
       View Release
    </a>

</div>

<div class="$ slide-right-in row clearfix" style="margin-top: 20px">
    <div class="col-md-6 column">
        <p>
            Build <?= $config["build"] ?>
        </p>
    </div>
    <div class="col-md-6 column">
        <p>
        Copyright <strong>(c)</strong> 2018 Pleets - DronePHP Framework module
        </p>
    </div>
</div>