<!DOCTYPE html>
<html id="extr-page">

<?php
	$config = include("module/DevZone/config/user.config.php");
	$fd = $config["routing"]["friendly"]
?>

<head>

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="icon" href="<?= $this->basePath() ?>/public/img/plts-favicon.png" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

	<?php $this->setTitle($config["project"]["name"]); $_title = $this->getTitle(); ?>

	<title><?= $this->getTitle() ?></title>

	<link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/css/plts-loaders.css" media="all" />
	<link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/lib/bootstrap-3.3.7/css/bootstrap.min.css" media="all" />

	<script type="text/javascript">
		window.onload = function()
		{
			var loader = document.getElementById("wrap-loader");

			if (loader.hasAttribute('style'))
			{
				loader.className = "$ fade-out fast";

				setTimeout(function(){
					loader.style.display = "none";
				}, 1000);
			}

			if (document.body !== undefined)
				document.body.style.overflow = "auto";
		}
	</script>

	<!-- Le Styles -->
	<link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/lib/CSS-Render/css-render.css" />

	<!-- Scripts -->
	<script type="text/javascript" src="<?= $this->basePath(); ?>/public/lib/jquery-2.1.1/jquery-2.1.1.min.js"></script>
	<script type="text/javascript" src="<?= $this->basePath(); ?>/public/lib/bootstrap-3.3.7/js/bootstrap.min.js"></script>

</head>

<body data-path='<?= $this->basePath(); ?>' class="$ animated fade-in normal-fast" ng-app="PortalCompras">

	<script type="text/javascript">
		document.body.style.overflow = "hidden";
	</script>

	<!-- Loader 7 -->
	<div id="wrap-loader" style="position: fixed; width: 100%; height: 100%; background: #8d054d; z-index: 100000; color: white">
		<div style='position: fixed; top: 50%; left: 50%; margin-left: -55px; margin-top: -55px;'>

			<div class='loader79'>
				<div class='one'></div>
				<div class='two'></div>
				<div class='three'></div>
			</div>

		</div>
	</div>

	<header id="header">

		<div style="background: rgb(240,240,240); padding: 10px; margin-bottom: 10px;">
			<a href="<?= $this->basePath() ?>/public/<?= ($fd) ? 'DevZone' : '?module=DevZone' ?>" class="btn btn-default">
				<span class="glyphicon glyphicon-console"></span>
				DevZone
			</a>
		</div>

	</header>

	<div id="main" role="main" style="padding-bottom: 20px">

		<!-- MAIN CONTENT -->
		<div id="content" class="container">
			<?= $this->content(); ?>
		</div>
	</div>

	<!-- update title -->
	<?php if ($this->getTitle() !== $_title): ?>
		<script type="text/javascript">
			$("head title").text($("head title").text() + ' - <?= $this->getTitle() ?>');
		</script>
	<?php endif; ?>

</body>

</html>