<!doctype html>
<html lang="en">

<html id="extr-page">

<?php
	$config = include("module/DevZone/config/user.config.php");
	$fd = $config["routing"]["friendly"]
?>

<head>

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="icon" href="<?= $this->basePath() ?>/public/img/plts-favicon.png" />
	<link rel="shortcut icon" href="<?= $this->basePath() ?>/public/img/favicon.png" />

	<!-- responsive metatag -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<?php $this->setTitle($config["project"]["name"]); $_title = $this->getTitle(); ?>

	<title><?= $this->getTitle() ?></title>

	<link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/css/bootstrap.min.css" />

</head>

<body>

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <a class="navbar-brand" href="<?= $this->basePath() ?>">
	  	<img src="<?= $this->basePath() ?>/public/img/bootstrap-solid.svg" height="30" width="30" class="d-inline-block align-top" alt="">
	  	Brand
	  </a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="#">Link</a>
	      </li>
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Dropdown
	        </a>
	        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
	          <a class="dropdown-item" href="#">Action</a>
	          <a class="dropdown-item" href="#">Another action</a>
	          <div class="dropdown-divider"></div>
	          <a class="dropdown-item" href="#">Something else here</a>
	        </div>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link disabled" href="#">Disabled</a>
	      </li>
	    </ul>
	    <form class="form-inline my-2 my-lg-0">
	      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
	      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
	    </form>
	  </div>
	</nav><br />

	<div class="container">
		<?= $this->content() ?>
	</div>

	<script src="<?= $this->basePath(); ?>/public/js/jquery-3.3.1.slim.min"></script>
	<script src="<?= $this->basePath(); ?>/public/js/popper-1.12.9.min"></script>
	<script src="<?= $this->basePath(); ?>/public/js/bootstrap.min.js"></script>

	<!-- update page title -->
	<?php if ($this->getTitle() !== $_title): ?>
		<script type="text/javascript">
			$("head title").text($("head title").text() + ' - <?= $this->getTitle() ?>');
		</script>
	<?php endif; ?>

</body>

</html>